services:
  cl_mailer.util.message_renderer:
    class: CL\Bundle\MailerBundle\Util\MessageRenderer
    arguments:
      # Engine to use will be overridden by RegisterRenderingEnginePass
      - @templating.engine.php

  cl_mailer.util.message_factory:
    class: CL\Bundle\MailerBundle\Util\MessageFactory
    arguments:
      - @cl_mailer.util.mailer_registry
      - @cl_mailer.util.message_renderer
      - @translator

  cl_mailer.util.mailer_registry:
    class: CL\Bundle\MailerBundle\Util\MailerRegistry

  cl_mailer.util.message_previewer:
    class: CL\Bundle\MailerBundle\Util\MessagePreviewer

  cl_mailer.util.mailer_helper:
    class: CL\Bundle\MailerBundle\Util\MailerHelper
    arguments:
      - @swiftmailer.mailer
      - @cl_mailer.util.message_factory

  cl_mailer.twig_extension.markdown_fallback:
    class: CL\Bundle\MailerBundle\Twig\MarkdownFallbackExtension
    arguments:
      - @twig
    tags:
      - { name: twig.extension }

  cl_mailer.mailer.welcome:
    class: CL\Bundle\MailerBundle\Mailer\WelcomeMailer
    arguments:
      - @cl_mailer.util.mailer_helper
